// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `AMD_Server_addUserToGroup.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Temporarily add a user to a group on a channel. This state is not saved, and is intended for temporary memberships.
 **/

public interface AMD_Server_addUserToGroup extends Ice.AMDCallback
{
    /**
     * ice_response indicates that
     * the operation completed successfully.
     **/
    void ice_response();
}
