// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_Meta_getSliceChecksums.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Returns a checksum dict for the slice file.
 **/

public abstract class Callback_Meta_getSliceChecksums extends Ice.TwowayCallback
{
    public abstract void response(java.util.Map<java.lang.String, java.lang.String> __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        MetaPrx __proxy = (MetaPrx)__result.getProxy();
        java.util.Map<java.lang.String, java.lang.String> __ret = null;
        try
        {
            __ret = __proxy.end_getSliceChecksums(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
