// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `MetaCallbackPrxHelper.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Callback interface for Meta. You can supply an implementation of this to receive notifications
 * when servers are stopped or started.
 * If an added callback ever throws an exception or goes away, it will be automatically removed.
 * Please note that all callbacks are done asynchronously; murmur does not wait for the callback to
 * complete before continuing processing.
 * @see ServerCallback
 * @see Meta.addCallback
 **/
public final class MetaCallbackPrxHelper extends Ice.ObjectPrxHelperBase implements MetaCallbackPrx
{
    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param srv Interface for started server.
     **/
    public void
    started(ServerPrx srv)
    {
        started(srv, null, false);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void
    started(ServerPrx srv, java.util.Map<String, String> __ctx)
    {
        started(srv, __ctx, true);
    }

    private void
    started(ServerPrx srv, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __delBase = __getDelegate(false);
                _MetaCallbackDel __del = (_MetaCallbackDel)__delBase;
                __del.started(srv, __ctx);
                return;
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __started_name = "started";

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     **/
    public Ice.AsyncResult begin_started(ServerPrx srv)
    {
        return begin_started(srv, null, false, null);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_started(ServerPrx srv, java.util.Map<String, String> __ctx)
    {
        return begin_started(srv, __ctx, true, null);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     **/
    public Ice.AsyncResult begin_started(ServerPrx srv, Ice.Callback __cb)
    {
        return begin_started(srv, null, false, __cb);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_started(ServerPrx srv, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_started(srv, __ctx, true, __cb);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     **/
    public Ice.AsyncResult begin_started(ServerPrx srv, Callback_MetaCallback_started __cb)
    {
        return begin_started(srv, null, false, __cb);
    }

    /**
     * Called when a server is started. The server is up and running when this event is sent, so all methods that 
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_started(ServerPrx srv, java.util.Map<String, String> __ctx, Callback_MetaCallback_started __cb)
    {
        return begin_started(srv, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_started(ServerPrx srv, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __started_name, __cb);
        try
        {
            __result.__prepare(__started_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            ServerPrxHelper.__write(__os, srv);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    /**
     * ice_response indicates that
     * the operation completed successfully.
     **/
    public void end_started(Ice.AsyncResult __result)
    {
        __end(__result, __started_name);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param srv Interface for started server.
     **/
    public void
    stopped(ServerPrx srv)
    {
        stopped(srv, null, false);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void
    stopped(ServerPrx srv, java.util.Map<String, String> __ctx)
    {
        stopped(srv, __ctx, true);
    }

    private void
    stopped(ServerPrx srv, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __delBase = __getDelegate(false);
                _MetaCallbackDel __del = (_MetaCallbackDel)__delBase;
                __del.stopped(srv, __ctx);
                return;
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __stopped_name = "stopped";

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     **/
    public Ice.AsyncResult begin_stopped(ServerPrx srv)
    {
        return begin_stopped(srv, null, false, null);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_stopped(ServerPrx srv, java.util.Map<String, String> __ctx)
    {
        return begin_stopped(srv, __ctx, true, null);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     **/
    public Ice.AsyncResult begin_stopped(ServerPrx srv, Ice.Callback __cb)
    {
        return begin_stopped(srv, null, false, __cb);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_stopped(ServerPrx srv, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_stopped(srv, __ctx, true, __cb);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     **/
    public Ice.AsyncResult begin_stopped(ServerPrx srv, Callback_MetaCallback_stopped __cb)
    {
        return begin_stopped(srv, null, false, __cb);
    }

    /**
     * Called when a server is stopped. The server is already stopped when this event is sent, so no methods that
     * need a running server will work.
     * @param __cb The callback object for the operation.
     * @param srv Interface for started server.
     * @param __ctx The Context map to send with the invocation.
     **/
    public Ice.AsyncResult begin_stopped(ServerPrx srv, java.util.Map<String, String> __ctx, Callback_MetaCallback_stopped __cb)
    {
        return begin_stopped(srv, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_stopped(ServerPrx srv, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __stopped_name, __cb);
        try
        {
            __result.__prepare(__stopped_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            ServerPrxHelper.__write(__os, srv);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    /**
     * ice_response indicates that
     * the operation completed successfully.
     **/
    public void end_stopped(Ice.AsyncResult __result)
    {
        __end(__result, __stopped_name);
    }

    public static MetaCallbackPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        MetaCallbackPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (MetaCallbackPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    MetaCallbackPrxHelper __h = new MetaCallbackPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MetaCallbackPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        MetaCallbackPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (MetaCallbackPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    MetaCallbackPrxHelper __h = new MetaCallbackPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static MetaCallbackPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MetaCallbackPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    MetaCallbackPrxHelper __h = new MetaCallbackPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MetaCallbackPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        MetaCallbackPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    MetaCallbackPrxHelper __h = new MetaCallbackPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static MetaCallbackPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        MetaCallbackPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (MetaCallbackPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                MetaCallbackPrxHelper __h = new MetaCallbackPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static MetaCallbackPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        MetaCallbackPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            MetaCallbackPrxHelper __h = new MetaCallbackPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::Murmur::MetaCallback"
    };

    public static String
    ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _MetaCallbackDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _MetaCallbackDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, MetaCallbackPrx v)
    {
        __os.writeProxy(v);
    }

    public static MetaCallbackPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            MetaCallbackPrxHelper result = new MetaCallbackPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
