// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ServerCallbackPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Callback interface for servers. You can supply an implementation of this to receive notification
 * messages from the server.
 * If an added callback ever throws an exception or goes away, it will be automatically removed.
 * Please note that all callbacks are done asynchronously; murmur does not wait for the callback to
 * complete before continuing processing.
 * Note that callbacks are removed when a server is stopped, so you should have a callback for
 * {@link MetaCallback.started} which calls {@link Server.addCallback}.
 * @see MetaCallback
 * @see Server.addCallback
 **/
public interface ServerCallbackPrx extends Ice.ObjectPrx
{
    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     **/
    public void userConnected(User state);

    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void userConnected(User state, java.util.Map<String, String> __ctx);

    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userConnected(User state);

    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userConnected(User state, java.util.Map<String, String> __ctx);

    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userConnected(User state, Ice.Callback __cb);

    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userConnected(User state, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userConnected(User state, Callback_ServerCallback_userConnected __cb);

    /**
     * Called when a user connects to the server. 
     * @param state State of connected user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userConnected(User state, java.util.Map<String, String> __ctx, Callback_ServerCallback_userConnected __cb);

    /**
     * Called when a user connects to the server. 
     * @param __result The asynchronous result object.
     **/
    public void end_userConnected(Ice.AsyncResult __result);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     **/
    public void userDisconnected(User state);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void userDisconnected(User state, java.util.Map<String, String> __ctx);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userDisconnected(User state);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userDisconnected(User state, java.util.Map<String, String> __ctx);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userDisconnected(User state, Ice.Callback __cb);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userDisconnected(User state, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userDisconnected(User state, Callback_ServerCallback_userDisconnected __cb);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param state State of disconnected user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userDisconnected(User state, java.util.Map<String, String> __ctx, Callback_ServerCallback_userDisconnected __cb);

    /**
     * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
     * to retrieve the user's state.
     * @param __result The asynchronous result object.
     **/
    public void end_userDisconnected(Ice.AsyncResult __result);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     **/
    public void userStateChanged(User state);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void userStateChanged(User state, java.util.Map<String, String> __ctx);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userStateChanged(User state);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userStateChanged(User state, java.util.Map<String, String> __ctx);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userStateChanged(User state, Ice.Callback __cb);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userStateChanged(User state, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userStateChanged(User state, Callback_ServerCallback_userStateChanged __cb);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param state New state of user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_userStateChanged(User state, java.util.Map<String, String> __ctx, Callback_ServerCallback_userStateChanged __cb);

    /**
     * Called when a user state changes. This is called if the user moves, is renamed, is muted, deafened etc.
     * @param __result The asynchronous result object.
     **/
    public void end_userStateChanged(Ice.AsyncResult __result);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     **/
    public void channelCreated(Channel state);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void channelCreated(Channel state, java.util.Map<String, String> __ctx);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelCreated(Channel state);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelCreated(Channel state, java.util.Map<String, String> __ctx);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelCreated(Channel state, Ice.Callback __cb);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelCreated(Channel state, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelCreated(Channel state, Callback_ServerCallback_channelCreated __cb);

    /**
     * Called when a new channel is created. 
     * @param state State of new channel.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelCreated(Channel state, java.util.Map<String, String> __ctx, Callback_ServerCallback_channelCreated __cb);

    /**
     * Called when a new channel is created. 
     * @param __result The asynchronous result object.
     **/
    public void end_channelCreated(Ice.AsyncResult __result);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     **/
    public void channelRemoved(Channel state);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void channelRemoved(Channel state, java.util.Map<String, String> __ctx);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelRemoved(Channel state);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelRemoved(Channel state, java.util.Map<String, String> __ctx);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelRemoved(Channel state, Ice.Callback __cb);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelRemoved(Channel state, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelRemoved(Channel state, Callback_ServerCallback_channelRemoved __cb);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param state State of removed channel.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelRemoved(Channel state, java.util.Map<String, String> __ctx, Callback_ServerCallback_channelRemoved __cb);

    /**
     * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
     * @param __result The asynchronous result object.
     **/
    public void end_channelRemoved(Ice.AsyncResult __result);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     **/
    public void channelStateChanged(Channel state);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     * @param __ctx The Context map to send with the invocation.
     **/
    public void channelStateChanged(Channel state, java.util.Map<String, String> __ctx);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelStateChanged(Channel state);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelStateChanged(Channel state, java.util.Map<String, String> __ctx);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelStateChanged(Channel state, Ice.Callback __cb);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelStateChanged(Channel state, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelStateChanged(Channel state, Callback_ServerCallback_channelStateChanged __cb);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param state New state of channel.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_channelStateChanged(Channel state, java.util.Map<String, String> __ctx, Callback_ServerCallback_channelStateChanged __cb);

    /**
     * Called when a new channel state changes. This is called if the channel is moved, renamed or if new links are added.
     * @param __result The asynchronous result object.
     **/
    public void end_channelStateChanged(Ice.AsyncResult __result);
}
