// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `UserInfoMapHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

public final class UserInfoMapHolder
{
    public
    UserInfoMapHolder()
    {
    }

    public
    UserInfoMapHolder(java.util.Map<UserInfo, java.lang.String> value)
    {
        this.value = value;
    }

    public java.util.Map<UserInfo, java.lang.String> value;
}
