// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `AMD_Server_getTree.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Fetch all channels and connected users as a tree. This retrieves an easy-to-use representation of the server
 * as a tree. This is primarily used for viewing the state of the server on a webpage.
 **/

public interface AMD_Server_getTree extends Ice.AMDCallback
{
    /**
     * ice_response indicates that
     * the operation completed successfully.
     * @param __ret (return value) Recursive tree of all channels and connected users.
     **/
    void ice_response(Tree __ret);
}
