// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_ServerUpdatingAuthenticator_getRegisteredUsers.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Get a list of registered users matching filter.
 **/

public abstract class Callback_ServerUpdatingAuthenticator_getRegisteredUsers extends Ice.TwowayCallback
{
    public abstract void response(java.util.Map<java.lang.Integer, java.lang.String> __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        ServerUpdatingAuthenticatorPrx __proxy = (ServerUpdatingAuthenticatorPrx)__result.getProxy();
        java.util.Map<java.lang.Integer, java.lang.String> __ret = null;
        try
        {
            __ret = __proxy.end_getRegisteredUsers(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
