// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_Meta_getVersion.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Fetch version of Murmur. 
 **/

public abstract class Callback_Meta_getVersion extends Ice.TwowayCallback
{
    public abstract void response(int major, int minor, int patch, String text);

    public final void __completed(Ice.AsyncResult __result)
    {
        MetaPrx __proxy = (MetaPrx)__result.getProxy();
        Ice.IntHolder major = new Ice.IntHolder();
        Ice.IntHolder minor = new Ice.IntHolder();
        Ice.IntHolder patch = new Ice.IntHolder();
        Ice.StringHolder text = new Ice.StringHolder();
        try
        {
            __proxy.end_getVersion(major, minor, patch, text, __result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(major.value, minor.value, patch.value, text.value);
    }
}
