// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_ServerCallback_userDisconnected.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Called when a user disconnects from the server. The user has already been removed, so you can no longer use methods like {@link Server.getState}
 * to retrieve the user's state.
 **/

public abstract class Callback_ServerCallback_userDisconnected extends Ice.OnewayCallback
{
}
