// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `LogEntry.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * A entry in the log.
 **/
public class LogEntry implements java.lang.Cloneable, java.io.Serializable
{
    /**
     * Timestamp in UNIX time_t
     **/
    public int timestamp;

    /**
     * The log message.
     **/
    public String txt;

    public LogEntry()
    {
    }

    public LogEntry(int timestamp, String txt)
    {
        this.timestamp = timestamp;
        this.txt = txt;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LogEntry _r = null;
        try
        {
            _r = (LogEntry)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(timestamp != _r.timestamp)
            {
                return false;
            }
            if(txt != _r.txt)
            {
                if(txt == null || _r.txt == null || !txt.equals(_r.txt))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        __h = 5 * __h + timestamp;
        if(txt != null)
        {
            __h = 5 * __h + txt.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(timestamp);
        __os.writeString(txt);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        timestamp = __is.readInt();
        txt = __is.readString();
    }
}
