// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ServerUpdatingAuthenticatorPrx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Callback interface for server authentication and registration. This allows you to support both authentication
 * and account updating.
 * You do not need to implement this if all you want is authentication, you only need this if other scripts
 * connected to the same server calls e.g. {@link Server.setTexture}.
 * Almost all of these methods support fall through, meaning murmur should continue the operation against its
 * own database.
 **/
public interface ServerUpdatingAuthenticatorPrx extends ServerAuthenticatorPrx
{
    /**
     * Register a new user.
     * @param info Information about user to register.
     * @return User id of new user, -1 for registration failure, or -2 to fall through.
     **/
    public int registerUser(java.util.Map<UserInfo, java.lang.String> info);

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param __ctx The Context map to send with the invocation.
     * @return User id of new user, -1 for registration failure, or -2 to fall through.
     **/
    public int registerUser(java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx);

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_registerUser(java.util.Map<UserInfo, java.lang.String> info);

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_registerUser(java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx);

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_registerUser(java.util.Map<UserInfo, java.lang.String> info, Ice.Callback __cb);

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_registerUser(java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_registerUser(java.util.Map<UserInfo, java.lang.String> info, Callback_ServerUpdatingAuthenticator_registerUser __cb);

    /**
     * Register a new user.
     * @param info Information about user to register.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_registerUser(java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx, Callback_ServerUpdatingAuthenticator_registerUser __cb);

    /**
     * Register a new user.
     * @param __result The asynchronous result object.
     * @return User id of new user, -1 for registration failure, or -2 to fall through.
     **/
    public int end_registerUser(Ice.AsyncResult __result);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @return 1 for successfull unregistration, 0 for unsuccessfull unregistration, -1 to fall through.
     **/
    public int unregisterUser(int id);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param __ctx The Context map to send with the invocation.
     * @return 1 for successfull unregistration, 0 for unsuccessfull unregistration, -1 to fall through.
     **/
    public int unregisterUser(int id, java.util.Map<String, String> __ctx);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_unregisterUser(int id);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_unregisterUser(int id, java.util.Map<String, String> __ctx);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_unregisterUser(int id, Ice.Callback __cb);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_unregisterUser(int id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_unregisterUser(int id, Callback_ServerUpdatingAuthenticator_unregisterUser __cb);

    /**
     * Unregister a user.
     * @param id Userid to unregister.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_unregisterUser(int id, java.util.Map<String, String> __ctx, Callback_ServerUpdatingAuthenticator_unregisterUser __cb);

    /**
     * Unregister a user.
     * @param __result The asynchronous result object.
     * @return 1 for successfull unregistration, 0 for unsuccessfull unregistration, -1 to fall through.
     **/
    public int end_unregisterUser(Ice.AsyncResult __result);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @return List of matching registered users.
     **/
    public java.util.Map<java.lang.Integer, java.lang.String> getRegisteredUsers(String filter);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param __ctx The Context map to send with the invocation.
     * @return List of matching registered users.
     **/
    public java.util.Map<java.lang.Integer, java.lang.String> getRegisteredUsers(String filter, java.util.Map<String, String> __ctx);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getRegisteredUsers(String filter);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getRegisteredUsers(String filter, java.util.Map<String, String> __ctx);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getRegisteredUsers(String filter, Ice.Callback __cb);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getRegisteredUsers(String filter, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getRegisteredUsers(String filter, Callback_ServerUpdatingAuthenticator_getRegisteredUsers __cb);

    /**
     * Get a list of registered users matching filter.
     * @param filter Substring usernames must contain. If empty, return all registered users.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getRegisteredUsers(String filter, java.util.Map<String, String> __ctx, Callback_ServerUpdatingAuthenticator_getRegisteredUsers __cb);

    /**
     * Get a list of registered users matching filter.
     * @param __result The asynchronous result object.
     * @return List of matching registered users.
     **/
    public java.util.Map<java.lang.Integer, java.lang.String> end_getRegisteredUsers(Ice.AsyncResult __result);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param info Information to set about user. This should be merged with existing information.
     * @return 1 for successfull update, 0 for unsuccessfull update, -1 to fall through.
     **/
    public int setInfo(int id, java.util.Map<UserInfo, java.lang.String> info);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param info Information to set about user. This should be merged with existing information.
     * @param __ctx The Context map to send with the invocation.
     * @return 1 for successfull update, 0 for unsuccessfull update, -1 to fall through.
     **/
    public int setInfo(int id, java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setInfo(int id, java.util.Map<UserInfo, java.lang.String> info);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setInfo(int id, java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setInfo(int id, java.util.Map<UserInfo, java.lang.String> info, Ice.Callback __cb);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setInfo(int id, java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setInfo(int id, java.util.Map<UserInfo, java.lang.String> info, Callback_ServerUpdatingAuthenticator_setInfo __cb);

    /**
     * Set additional information for user registration.
     * @param id Userid of registered user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setInfo(int id, java.util.Map<UserInfo, java.lang.String> info, java.util.Map<String, String> __ctx, Callback_ServerUpdatingAuthenticator_setInfo __cb);

    /**
     * Set additional information for user registration.
     * @param __result The asynchronous result object.
     * @return 1 for successfull update, 0 for unsuccessfull update, -1 to fall through.
     **/
    public int end_setInfo(Ice.AsyncResult __result);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param tex New texture.
     * @return 1 for successfull update, 0 for unsuccessfull update, -1 to fall through.
     **/
    public int setTexture(int id, byte[] tex);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param tex New texture.
     * @param __ctx The Context map to send with the invocation.
     * @return 1 for successfull update, 0 for unsuccessfull update, -1 to fall through.
     **/
    public int setTexture(int id, byte[] tex, java.util.Map<String, String> __ctx);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setTexture(int id, byte[] tex);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setTexture(int id, byte[] tex, java.util.Map<String, String> __ctx);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setTexture(int id, byte[] tex, Ice.Callback __cb);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setTexture(int id, byte[] tex, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setTexture(int id, byte[] tex, Callback_ServerUpdatingAuthenticator_setTexture __cb);

    /**
     * Set texture (now called avatar) of user registration.
     * @param id registrationId of registered user.
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_setTexture(int id, byte[] tex, java.util.Map<String, String> __ctx, Callback_ServerUpdatingAuthenticator_setTexture __cb);

    /**
     * Set texture (now called avatar) of user registration.
     * @param __result The asynchronous result object.
     * @return 1 for successfull update, 0 for unsuccessfull update, -1 to fall through.
     **/
    public int end_setTexture(Ice.AsyncResult __result);
}
