// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ServerCallbackPrxHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

public final class ServerCallbackPrxHolder
{
    public
    ServerCallbackPrxHolder()
    {
    }

    public
    ServerCallbackPrxHolder(ServerCallbackPrx value)
    {
        this.value = value;
    }

    public ServerCallbackPrx value;
}
